name: code scanning

on: 
    push:
        branches: [main]

jobs:
    scan-code:
        runs-on: ubuntu-latest

        steps:
        - name: code scanning
          uses: actions/checkout@v4

        - name: Set up JDK
          uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: '21'
            cache: 'maven'
        
        - name: Build the code with maven
          run: mvn clean install -DskipTests 

        - name: Initialize CodeQL
          uses: github/codeql-action/init@v3
          with:
            languages: 'java-kotlin'
            queries: security-extended 