name: DevSecOps End-to-end Pipeline

on:
  push:
    branches: [main]

jobs:

  code-scan:
    name: code-quality
    uses: ./.github/workflows/code-scan.yml
    permissions:
      security-events: write
      actions: read
      packages: read

  secrets-scan:
    name: secrets-scan
    uses: ./.github/workflows/secrets-scan.yml
    permissions:
      security-events: write
      actions: read

  dependency-scan:
    name: dependecy-scan
    uses: ./.github/workflows/dependecy-scan.yml
    permissions:
      security-events: write
      actions: read

  docker-lint:
    name: docker-scan
    uses: ./.github/workflows/docker-lint.yml
    permissions:
      actions: read

  build:
    name: build
    needs: [code-scan, secrets-scan, dependency-scan, docker-lint]
    uses: ./.github/workflows/docker-build-push.yml
    permissions:
      contents: read
      packages: write
    secrets: inherit

  trivy:
    name: trivy
    needs: build
    uses: ./.github/workflows/image-scan.yml
    permissions:
      security-events: write
      actions: read
    secrets: inherit

  deploy:
    name: deploy
    needs: trivy
    uses: ./.github/workflows/deploy-to-server.yml
    secrets: inherit