# name: docker linting

# on:
#     workflow_call:

# jobs:
#     docker-linting:
#         runs-on: ubuntu-latest
#         steps:
#             - name: checkout the Code
#               uses: actions/checkout@v4

            